import { describe, expect, it } from "vitest";
import { readTree } from "test/support/readTree.ts";
import { runStub } from "test/support/runStub.ts";
import { useExample } from "test/support/useExample.ts";

/** An example's own README is input, like its `.stub` — only what the run wrote is under test. */
const generatedTree = (projectRoot: string): Record<string, string> =>
    Object.fromEntries(Object.entries(readTree(projectRoot)).filter(([file]) => file !== "README.md"));

/**
 * The shipped `examples/` are the happy path: what the README and the docs site quote, and what a new
 * user copies. Running them here is what stops a broken example from being someone's first impression.
 * `test/fixtures/` deliberately holds only the pathological cases.
 */
describe("examples", () => {
    it("renders examples/basic exactly as its README documents", () => {
        const projectRoot = useExample("basic");

        const { status, stdout } = runStub(projectRoot, ["greeting", "world peace"]);

        expect(status).toBe(0);
        expect(stdout.trim().split("\n")).toHaveLength(1);
        expect(generatedTree(projectRoot)).toEqual({ "out/world-peace.txt": "Hello, World Peace!\n" });
    });

    it("renders examples/module exactly as its README documents", () => {
        const projectRoot = useExample("module");

        const { status, stdout } = runStub(projectRoot, ["model", "Invoice"]);

        expect(status).toBe(0);
        expect(stdout.trim().split("\n")).toHaveLength(3);
        expect(generatedTree(projectRoot)).toMatchInlineSnapshot(`
          {
            "src/invoices/Invoice.ts": "// Generated by stub. Model: src/invoices/Invoice.ts
          // Regenerate it rather than editing it — the source of truth is .stub/.

          export interface Invoice {
              id: string;
              label: string;
              createdAt: string;
          }

          /** New invoice fields — the store adds id and createdAt. */
          export type NewInvoice = Omit<Invoice, "id" | "createdAt">;
          ",
            "src/invoices/invoiceStore.ts": "// Generated by stub. Model: src/invoices/Invoice.ts
          // Regenerate it rather than editing it — the source of truth is .stub/.

          import type { Invoice, NewInvoice } from "./Invoice";

          const invoices = new Map<string, Invoice>();

          export const addInvoice = (draft: NewInvoice): Invoice => {
              const invoice = { ...draft, id: String(invoices.size + 1), createdAt: new Date().toISOString() };

              invoices.set(invoice.id, invoice);
              return invoice;
          };

          export const listInvoices = (): Array<Invoice> => [...invoices.values()];

          export const removeInvoice = (id: string): boolean => invoices.delete(id);
          ",
            "tests/invoices/Invoice.test.ts": "import assert from "node:assert/strict";
          import { test } from "node:test";
          import type { NewInvoice } from "@/invoices/Invoice";
          import { addInvoice, listInvoices } from "@/invoices/invoiceStore";

          test("stores a new invoice", () => {
              const draft: NewInvoice = { label: "first" };

              addInvoice(draft);

              assert.equal(listInvoices().length, 1);
          });
          ",
          }
        `);
    });

    it("renders examples/module with every switch and override its README shows", () => {
        const projectRoot = useExample("module");

        const { status } = runStub(projectRoot, ["model", "Invoice", "--noDelete", "--entityPlural", "Invoicen"]);
        const generated = generatedTree(projectRoot);

        expect(status).toBe(0);

        // The override reaches `dir`, and therefore every template in the chain — including the one
        // whose own `dir` computed shadows the global.
        expect(Object.keys(generated)).toEqual([
            "src/invoicen/Invoice.ts",
            "src/invoicen/invoiceStore.ts",
            "tests/invoicen/Invoice.test.ts",
        ]);

        // A switch removes content inside a body, never a file.
        expect(generated["src/invoicen/invoiceStore.ts"]).not.toContain("removeInvoice");
        expect(generated["src/invoicen/invoiceStore.ts"]).toContain("listInvoicen");
    });

    it("renders only the entry named when --noRequires precedes the command", () => {
        const projectRoot = useExample("module");

        const { status } = runStub(projectRoot, ["--noRequires", "model", "Invoice"]);

        expect(status).toBe(0);
        // The banner's `{% path "model" %}` still resolves, because targets are resolved for the whole
        // manifest rather than for the chain this run writes.
        expect(Object.keys(generatedTree(projectRoot))).toEqual(["src/invoices/Invoice.ts"]);
    });
});
